name: Secret scanner
on: 
  push:
    branches:
      - dev
      - master
      - release/*
    pull_request:
      branches:
        - dev
        - master

jobs:
  build:
    name: Scanning for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan for secrets
        uses: eshork/gitleaks-action@master
